spring:
  application:
    name: bff

server:
  port: 8080

auth-service:
  url: https://ms-auth-mj1u.onrender.com/api/v1/auth

user-service:
  url: https://ms-auth-mj1u.onrender.com/api/v1/users

account/transfer-service:
  url: https://ms-transfer.onrender.com/api/v1/accounts

currency-service:
  url: https://ms-transfer.onrender.com/api/v1/rates


feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: FULL

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
